---
title: "Data Cleaning"
author: "Tom Gibbens-Matsuyama"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

### Load libraries

```{r}
library(tidyverse)
library(here)
library(janitor)
```

### Load data

```{r}

# Product data
crop_yield <- read_csv(here("data", "FAOSTAT_data_en_4-1-2025.csv")) %>% 
  clean_names()

# Calendar data
crop_calendar <- read_csv(here("data", "crop_yields.csv")) %>% 
  clean_names()
```

### Start the cleaning process

```{r}

# Product data cleaning
crop_yield_cleaned <- crop_yield %>% 
  rename(country = area,
         crop = item) %>% 
  select(c(country, crop, item_code_cpc, element, element_code,
           year, unit, value, flag_description, flag, domain, domain_code)) %>% 
  filter(crop %in% c("Wheat", "Rye", "Rice", "Oats", "Barley"),
         year == 2023)

# Create unique ID
crop_yield_cleaned$unique_id <- as.integer(factor(paste(crop_yield_cleaned$country,
                                               crop_yield_cleaned$item,
                                               crop_yield_cleaned$element,
                                               crop_yield_cleaned$year))) 

crop_yield_cleaned <- crop_yield_cleaned %>% 
  drop_na()



# Calendar data cleaning
crop_calendar_cleaned <- crop_calendar %>% 
  rename(country = location) %>% 
  select(c(data_id, country, crop, plant_start, plant_end, plant_range,
           harvest_start, harvest_end, harvest_range, temp_average, precip_average)) %>% 
  filter(crop %in% c("Wheat", "Rye", "Rice", "Oats", "Barley"))

crop_calendar_cleaned <- crop_calendar_cleaned %>% 
  drop_na()
```

```{r}
# Check NA values for Crop Yield
for (col in names(crop_yield_cleaned)) {
  num_na <- sum(is.na(crop_yield_cleaned[[col]]))
  if (num_na > 0) {
    cat(col, "has", num_na, "NA values\n")
  } else {
    cat(col, "has no NA values\n")
  }
}

# Check NA values for crop calendar
for (col in names(crop_calendar_cleaned)) {
  num_na <- sum(is.na(crop_calendar_cleaned[[col]]))
  if (num_na > 0) {
    cat(col, "has", num_na, "NA values\n")
  } else {
    cat(col, "has no NA values\n")
  }
}
```


```{r}
write_csv(crop_yield_cleaned, "crop_yield_cleaned.csv")

write_csv(crop_calendar_cleaned, "crop_cal_cleaned.csv")
```

